CC = gcc
CFLAGS = -Wall -Werror -std=gnu11 -g -O2 -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64

all : gai gai6 conn serv

gai : gai.c

gai6 : gai6.c

conn : conn.c

serv : serv.c

clean :
	-rm -f gai gai6 conn serv
