CC = gcc
CFLAGS = -O2 -g -Wall -std=gnu11
CXX = g++
CXXFLAGS = -O2 -g -Wall -std=gnu++14

TARGETS = pp pp2 pp3 sum pp_bad fiford fifowr div0 div0sig div0sigex

all : $(TARGETS)

clean :
	-rm -f $(TARGETS)

