CXX = g++
CXXFLAGS = -Wall -O2 -g -std=gnu++14 -pthread
TARGETS = bank1 bank2 bank3 bank4 bank5 bank6 barrier

all : $(TARGETS)

bank1 : bank1.cpp
bank2 : bank2.cpp
bank3 : bank3.cpp
bank4 : bank4.cpp
bank5 : bank5.cpp
bank6 : bank6.cpp
barrier : barrier.cpp

clean :
	-rm -f $(TARGETS)
